// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __IHelloWorld_hh__
#define __IHelloWorld_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE First

_CORBA_MODULE_BEG

#ifndef __First_mIHello__
#define __First_mIHello__
  class IHello;
  class _objref_IHello;
  class _impl_IHello;
  
  typedef _objref_IHello* IHello_ptr;
  typedef IHello_ptr IHelloRef;

  class IHello_Helper {
  public:
    typedef IHello_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_IHello, IHello_Helper> IHello_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_IHello,IHello_Helper > IHello_out;

#endif

  // interface IHello
  class IHello {
  public:
    // Declarations for this interface type.
    typedef IHello_ptr _ptr_type;
    typedef IHello_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_IHello :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Long AddValue(::CORBA::Long a, ::CORBA::Long b);
    ::CORBA::WChar* SayHello(const ::CORBA::WChar* name);
    void SayHello2(const char* name, ::CORBA::String_out greeting);
    ::CORBA::Boolean Message(::CORBA::String_INOUT_arg message);

    // Constructors
    inline _objref_IHello()  { _PR_setobj(0); }  // nil
    _objref_IHello(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_IHello();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_IHello(const _objref_IHello&);
    _objref_IHello& operator = (const _objref_IHello&);
    // not implemented

    friend class IHello;
  };

  class _pof_IHello : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_IHello() : _OMNI_NS(proxyObjectFactory)(IHello::_PD_repoId) {}
    virtual ~_pof_IHello();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_IHello :
    public virtual omniServant
  {
  public:
    virtual ~_impl_IHello();

    virtual ::CORBA::Long AddValue(::CORBA::Long a, ::CORBA::Long b) = 0;
    virtual ::CORBA::WChar* SayHello(const ::CORBA::WChar* name) = 0;
    virtual void SayHello2(const char* name, ::CORBA::String_out greeting) = 0;
    virtual ::CORBA::Boolean Message(char*& message) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_First
_CORBA_MODULE_BEG

  class IHello :
    public virtual First::_impl_IHello,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~IHello();

    inline ::First::IHello_ptr _this() {
      return (::First::IHello_ptr) _do_this(::First::IHello::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_First
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
First::IHello::_marshalObjRef(::First::IHello_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_IHelloWorld
#endif

#endif  // __IHelloWorld_hh__

