// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __server_hh__
#define __server_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_server
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_server
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_server
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE test

_CORBA_MODULE_BEG

#ifndef __test_mIServer__
#define __test_mIServer__
  class IServer;
  class _objref_IServer;
  class _impl_IServer;
  
  typedef _objref_IServer* IServer_ptr;
  typedef IServer_ptr IServerRef;

  class IServer_Helper {
  public:
    typedef IServer_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_IServer, IServer_Helper> IServer_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_IServer,IServer_Helper > IServer_out;

#endif

  // interface IServer
  class IServer {
  public:
    // Declarations for this interface type.
    typedef IServer_ptr _ptr_type;
    typedef IServer_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_IServer :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Long add(::CORBA::Long agr1, ::CORBA::Long arg2);

    // Constructors
    inline _objref_IServer()  { _PR_setobj(0); }  // nil
    _objref_IServer(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_IServer();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_IServer(const _objref_IServer&);
    _objref_IServer& operator = (const _objref_IServer&);
    // not implemented

    friend class IServer;
  };

  class _pof_IServer : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_IServer() : _OMNI_NS(proxyObjectFactory)(IServer::_PD_repoId) {}
    virtual ~_pof_IServer();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_IServer :
    public virtual omniServant
  {
  public:
    virtual ~_impl_IServer();

    virtual ::CORBA::Long add(::CORBA::Long agr1, ::CORBA::Long arg2) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_test
_CORBA_MODULE_BEG

  class IServer :
    public virtual test::_impl_IServer,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~IServer();

    inline ::test::IServer_ptr _this() {
      return (::test::IServer_ptr) _do_this(::test::IServer::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_test
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
test::IServer::_marshalObjRef(::test::IServer_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_server
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_server
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_server
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_server
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_server
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_server
#endif

#endif  // __server_hh__

