// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "server.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



test::IServer_ptr test::IServer_Helper::_nil() {
  return ::test::IServer::_nil();
}

::CORBA::Boolean test::IServer_Helper::is_nil(::test::IServer_ptr p) {
  return ::CORBA::is_nil(p);

}

void test::IServer_Helper::release(::test::IServer_ptr p) {
  ::CORBA::release(p);
}

void test::IServer_Helper::marshalObjRef(::test::IServer_ptr obj, cdrStream& s) {
  ::test::IServer::_marshalObjRef(obj, s);
}

test::IServer_ptr test::IServer_Helper::unmarshalObjRef(cdrStream& s) {
  return ::test::IServer::_unmarshalObjRef(s);
}

void test::IServer_Helper::duplicate(::test::IServer_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

test::IServer_ptr
test::IServer::_duplicate(::test::IServer_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

test::IServer_ptr
test::IServer::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


test::IServer_ptr
test::IServer::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

test::IServer_ptr
test::IServer::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_IServer _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_IServer* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_IServer;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* test::IServer::_PD_repoId = "IDL:test/IServer:1.0";


test::_objref_IServer::~_objref_IServer() {
  
}


test::_objref_IServer::_objref_IServer(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::test::IServer::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
test::_objref_IServer::_ptrToObjRef(const char* id)
{
  if (id == ::test::IServer::_PD_repoId)
    return (::test::IServer_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::test::IServer::_PD_repoId))
    return (::test::IServer_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for test::IServer::add

// Proxy call descriptor class. Mangled signature:
//  _clong_i_clong_i_clong
class _0RL_cd_7407888c69641630_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7407888c69641630_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Long result;
};

void _0RL_cd_7407888c69641630_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_7407888c69641630_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1 <<= _n;

}

void _0RL_cd_7407888c69641630_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_7407888c69641630_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_7407888c69641630_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7407888c69641630_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7407888c69641630_00000000* tcd = (_0RL_cd_7407888c69641630_00000000*)cd;
  test::_impl_IServer* impl = (test::_impl_IServer*) svnt->_ptrToInterface(test::IServer::_PD_repoId);
  tcd->result = impl->add(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long test::_objref_IServer::add(::CORBA::Long agr1, ::CORBA::Long arg2)
{
  _0RL_cd_7407888c69641630_00000000 _call_desc(_0RL_lcfn_7407888c69641630_10000000, "add", 4);
  _call_desc.arg_0 = agr1;
  _call_desc.arg_1 = arg2;

  _invoke(_call_desc);
  return _call_desc.result;


}

test::_pof_IServer::~_pof_IServer() {}


omniObjRef*
test::_pof_IServer::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::test::_objref_IServer(ior, id);
}


::CORBA::Boolean
test::_pof_IServer::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::test::IServer::_PD_repoId))
    return 1;
  
  return 0;
}

const test::_pof_IServer _the_pof_test_mIServer;

test::_impl_IServer::~_impl_IServer() {}


::CORBA::Boolean
test::_impl_IServer::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "add")) {

    _0RL_cd_7407888c69641630_00000000 _call_desc(_0RL_lcfn_7407888c69641630_10000000, "add", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
test::_impl_IServer::_ptrToInterface(const char* id)
{
  if (id == ::test::IServer::_PD_repoId)
    return (::test::_impl_IServer*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::test::IServer::_PD_repoId))
    return (::test::_impl_IServer*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
test::_impl_IServer::_mostDerivedRepoId()
{
  return ::test::IServer::_PD_repoId;
}

POA_test::IServer::~IServer() {}

