#ifndef org_uneta_iiopnet_examples_first
#define org_uneta_iiopnet_examples_first

#pragma prefix "Org.Uneta.Iiopnet.Examples"

module First
{
	struct MyComplexNumber
	{
		long re;
		long im;
	};

	struct MyOtherDataType
	{
		long re;
		long im;
	};

	interface IHello
	{
		exception UserExceptionS{};
		exception UserExceptionExt{ string reason; long codeError; };

		long AddValue(in long a, in long b);		
		wstring SayHello(in wstring name);
		void SayHello2(in string name, out string greeting);
		boolean Message(inout string message);
		MyComplexNumber MulComplex(in MyComplexNumber x, inout MyComplexNumber y); //for testing purpose inout should just return same data as return value
		boolean MulComplexAsAny(in any x, in any y, out any result);
		void DataTimeTransfer(inout long long DataTimeValue);
		void ThrowExceptions(in long excptionVariant) raises(UserExceptionS, UserExceptionExt);
	};
};

#endif